# Generated by Django 5.0 on 2024-04-25 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('albumId', models.AutoField(primary_key=True, serialize=False)),
                ('albumCoverPath', models.CharField(max_length=200, null=True)),
                ('albumDuration', models.CharField(max_length=10, null=True)),
                ('albumGenre', models.CharField(max_length=25)),
                ('albumName', models.CharField(max_length=50)),
                ('albumReleaseDateTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=25)),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userDisplayName', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userIdFk', models.IntegerField()),
                ('followsIdFk', models.IntegerField()),
            ],
            options={
                'db_table': 'following',
                'unique_together': {('userIdFk', 'followsIdFk')},
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userIdFk', models.IntegerField()),
                ('trackIdFk', models.IntegerField()),
                ('likeDateTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'likes',
                'unique_together': {('userIdFk', 'trackIdFk', 'likeDateTime')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackIdFk', models.IntegerField()),
                ('playlistIdFk', models.IntegerField()),
                ('trackOrder', models.IntegerField()),
            ],
            options={
                'db_table': 'playlistTracks',
                'unique_together': {('trackIdFk', 'playlistIdFk')},
            },
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('trackDuration', models.CharField(max_length=10, null=True)),
                ('trackGenre', models.CharField(max_length=25)),
                ('trackId', models.AutoField(primary_key=True, serialize=False)),
                ('trackName', models.CharField(max_length=50)),
                ('trackPath', models.CharField(max_length=200)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.albums')),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('playlistCoverPath', models.CharField(max_length=200)),
                ('playlistDateTime', models.DateTimeField(auto_now_add=True)),
                ('playlistDuration', models.CharField(max_length=10, null=True)),
                ('playlistId', models.AutoField(primary_key=True, serialize=False)),
                ('playlistName', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.users')),
            ],
            options={
                'db_table': 'playlists',
            },
        ),
        migrations.AddField(
            model_name='albums',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.users'),
        ),
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userIdFk', models.IntegerField()),
                ('trackIdFk', models.IntegerField()),
                ('playDateTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'userTracks',
                'unique_together': {('userIdFk', 'trackIdFk', 'playDateTime')},
            },
        ),
    ]
