# Generated by Django 5.0 on 2024-04-24 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_display_name',
            new_name='userDisplayName',
        ),
    ]
